#pragma config(Sensor, dgtl5,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  red,            sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightBack,     tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           rightFront,    tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           leftBack,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           leftFront,     tmotorVex393_MC29, openLoop, driveLeft)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"


#define MIN 0.5


void pre_auton()
{

	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}



// function defined by user that takes two parameters, left and right. changes value of motor port given in square braces.
void move(float left, float right) {
	motor[leftFront] = left;
	motor[leftBack] = left;
	motor[rightFront] = right;
	motor[rightBack] = right;
}

task autonomous()
{
	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{

	bool toggleState;
	int prevButtonState;
	int buttonState;


	while (true)
	{
		// sets yellow LED to buttonState for current loop of code, which is set by the state of Btn8D.
		SensorValue[yellow] = buttonState = vexRT[Btn8D];

		// easily settable range for move
		if (toggleState) {
			move((vexRT[Ch3] * 0.5) + (vexRT[Ch4] * 0.5), (vexRT[Ch3] * 0.5) - (vexRT[Ch4] * 0.5));
		}
		else move((vexRT[Ch3] * 0.6) + (vexRT[Ch4] * 0.6), (vexRT[Ch3] * 0.6) - (vexRT[Ch4] * 0.6));

		// reverses state of toggle if button is pressed and wasn't pressed in previous loop.
		if (buttonState && prevButtonState != buttonState)
		{
			SensorValue[red] = toggleState = !toggleState;
		}

		// sets prevButtonState to curr. button state.
		prevButtonState = buttonState;
	}
}
