#pragma config(Sensor, dgtl5,  green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  yellow,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  red,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           rightBack,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightFront,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           leftBack,      tmotorNone, openLoop)
#pragma config(Motor,  port4,           leftFront,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/


void driveSpeed(float left, float right)
{
	motor[leftFront] = left;
	motor[leftBack] = left;
	motor[rightFront] = right;
	motor[rightBack] = right;
}


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	// ..........................................................................
	// Insert user code here.
	// ..........................................................................

	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

/*---------------------------------------------------------------------------*
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{

	bool toggleState = true;
	int prevButtonState, buttonState;

	// sets precision multiplier, joystick value is multiplied by this.
	float mult = 0.5;

	while (true)
	{
		// sets yellow LED to buttonState for current loop of code, which is set by the state of Btn8D.
		SensorValue[yellow] = buttonState = vexRT[Btn8D];

		// easily settable range for driveSpeed
		if (toggleState) driveSpeed(vexRT[Ch3], vexRT[Ch2]);
		else             driveSpeed(vexRT[Ch3] * mult, driveSpeed(vexRT[Ch2] * mult);



		// reverses state of toggle if button is pressed and wasn't pressed in previous loop.
		if (buttonState && prevButtonState != buttonState)
		{
			SensorValue[red] = toggleState = !toggleState;
		}

		// sets prevButtonState to curr. button state. Used
		prevButtonState = buttonState;
	}
}
